### ISSUE TITLE
Fix test_revision_flow functional test flakiness

### ISSUE THREAD

**Issue by metakuni** [chanzuckerberg/single-cell-data-portal#1446]
From a CI functional test run a couple of days ago:

```
======================================================================
ERROR: test_revision_flow (tests.functional.backend.corpora.test_revisions.TestRevisions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/corpora-data-portal/tests/functional/backend/corpora/test_revisions.py", line 66, in test_revision_flow
    schema_before_revision_res.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: NOT FOUND for url: https://api.cellxgene.staging.single-cell.czi.technology/cellxgene/e/0d8db00e-a741-47d4-b916-40800e83ddb7.cxg/api/v0.2/schema
```

This was happening because the test was hitting the schema endpoint too early.

**Comment by metakuni** [comment]
Functional tests are failing again so moving this back to in progress.
