### ISSUE TITLE
Fix Portal's CI/CD

### ISSUE THREAD

**Issue by metakuni** [chanzuckerberg/single-cell-data-portal#1475]
The `push-image` job of the `Push tests` workflow [started failing on 2021-09-29](https://github.com/chanzuckerberg/single-cell-data-portal/runs/3738793604?check_suite_focus=true#step:5:39):

```
Traceback (most recent call last):
  File "scripts/happy", line 1282, in <module>
    cli.main(obj=obj)
  File "/home/runner/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/runner/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/runner/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/runner/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/runner/.local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "scripts/happy", line 1082, in addtags
    manifest = manifest["images"][0]["imageManifest"]
IndexError: list index out of range
Error: Process completed with exit code 1.
```

Long story short, `push-image` invokes `happy` as:

```
scripts/happy --profile="" addtags --source-tag sha-${GITHUB_SHA:0:8} --dest-tag branch-$(echo ${GITHUB_REF#refs/heads/} | sed 's/[\+\/]/-/g')
```

Since it's invoked with `profile=""`, `happy` does a fallback and reads its configuration from [`happy/env-rdev-config`](https://us-west-2.console.aws.amazon.com/secretsmanager/home?region=us-west-2#!/secret?name=happy%2Fenv-rdev-config). 

As a result of the ongoing work to move Explorer to ECS deployment, the Explorer ECR repo was added to the `ecrs` list in this config:

```
...
  "ecrs": {
    "backend": {
      "url": "699936264352.dkr.ecr.us-west-2.amazonaws.com/corpora-backend"
    },
    "explorer": {
      "url": "699936264352.dkr.ecr.us-west-2.amazonaws.com/corpora-explorer"
    },
...
```

. Since Explorer images with the same tag as Portal don't yet exit, `happy` was failing when trying to retrieve metadata for Explorer images.

**Comment by metakuni** [comment]
The expected commit `7bfe4e0a` has been auto-deployed to `dev`:
```
$ curl https://api.cellxgene.dev.single-cell.czi.technology/dp/v1/deployed_version
{
  "Data Portal": "7bfe4e0a21aababeab35feadcf416a20208c491b"
}
```
