### ISSUE TITLE
BE Crossref unit tests failing locally and not running in the pipeline

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [chanzuckerberg/single-cell-data-portal#2528]
#### Local Errors
```
> make unit-test path=tests/unit/backend/corpora/common/providers/test_crossref_provider.py
Running specified backend unit test(s): tests/unit/backend/corpora/common/providers/test_crossref_provider.py
Creating single-cell-data-portal_backend_run ... done
FEF.E.
======================================================================
ERROR: test__provider_does_not_call_crossref_in_test (tests.unit.backend.corpora.common.providers.test_crossref_provider.TestCrossrefProvider)
----------------------------------------------------------------------
Traceback (most recent call last):
 File "/corpora-data-portal/backend/corpora/common/providers/crossref_provider.py", line 80, in fetch_metadata
  message = res.json()["message"]
AttributeError: 'NoneType' object has no attribute 'json'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
 File "/usr/lib/python3.9/unittest/mock.py", line 1337, in patched
  return func(*newargs, **newkeywargs)
 File "/corpora-data-portal/tests/unit/backend/corpora/common/providers/test_crossref_provider.py", line 18, in test__provider_does_not_call_crossref_in_test
  res = provider.fetch_metadata("test_doi")
 File "/corpora-data-portal/backend/corpora/common/providers/crossref_provider.py", line 135, in fetch_metadata
  raise CrossrefParseException("Cannot parse metadata from Crossref") from e
backend.corpora.common.providers.crossref_provider.CrossrefParseException: Cannot parse metadata from Crossref
======================================================================
ERROR: test__provider_throws_exception_if_request_fails (tests.unit.backend.corpora.common.providers.test_crossref_provider.TestCrossrefProvider)
Asserts a CrossrefFetchException if the GET request fails for any reason
----------------------------------------------------------------------
Traceback (most recent call last):
 File "/corpora-data-portal/backend/corpora/common/providers/crossref_provider.py", line 57, in _fetch_crossref_payload
  res = requests.get(
 File "/usr/lib/python3.9/unittest/mock.py", line 1093, in __call__
  return self._mock_call(*args, **kwargs)
 File "/usr/lib/python3.9/unittest/mock.py", line 1097, in _mock_call
  return self._execute_mock_call(*args, **kwargs)
 File "/usr/lib/python3.9/unittest/mock.py", line 1152, in _execute_mock_call
  raise effect
Exception: Mocked CrossrefFetchException
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
 File "/usr/lib/python3.9/unittest/mock.py", line 1337, in patched
  return func(*newargs, **newkeywargs)
 File "/corpora-data-portal/tests/unit/backend/corpora/common/providers/test_crossref_provider.py", line 149, in test__provider_throws_exception_if_request_fails
  provider.fetch_metadata("test_doi")
 File "/corpora-data-portal/backend/corpora/common/providers/crossref_provider.py", line 77, in fetch_metadata
  res = self._fetch_crossref_payload(doi)
 File "/corpora-data-portal/backend/corpora/common/providers/crossref_provider.py", line 63, in _fetch_crossref_payload
  if res.status_code == 404:
UnboundLocalError: local variable 'res' referenced before assignment
======================================================================
FAIL: test__provider_calls_crossref_if_api_key_defined (tests.unit.backend.corpora.common.providers.test_crossref_provider.TestCrossrefProvider)
----------------------------------------------------------------------
Traceback (most recent call last):
 File "/usr/lib/python3.9/unittest/mock.py", line 1337, in patched
  return func(*newargs, **newkeywargs)
 File "/corpora-data-portal/tests/unit/backend/corpora/common/providers/test_crossref_provider.py", line 70, in test__provider_calls_crossref_if_api_key_defined
  self.assertDictEqual(expected_response, res)
AssertionError: {'aut[141 chars]y': 10, 'published_at': 1636520400.0, 'journal[29 chars]alse} != {'aut[141 chars]y': 18, 'published_at': 1637193600.0, 'journal[29 chars]alse}
 {'authors': [{'family': 'Doe', 'given': 'John'},
        {'family': 'Doe', 'given': 'Jane'}],
  'is_preprint': False,
  'journal': 'Nature',
- 'published_at': 1636520400.0,
?           ----
+ 'published_at': 1637193600.0,
?           ++++
- 'published_day': 10,
?          ^
+ 'published_day': 18,
?          ^
  'published_month': 11,
  'published_year': 2021}
======================================================================
```
#### Pipeline
The Crossref unit tests are not currently running in the testing pipeline.

**Comment by metakuni** [comment]
@ebezzi : Still relevant?
