### ISSUE TITLE
Create standalone 'remove-labels' command for cellxgene-schema CLI

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell-data-portal#3268]
Add CLI command that removes portal-added labels from h5ads, so curators revising existing datasets may download them from the portal and re-submit them after curation without the manual step of removing all portal-added labels (which will fail validation)

**Comment by nayib-jose-gloria** [comment]
cellxgene-schema CLI release candidate to test these changes against: https://drive.google.com/file/d/1o9unTUFV7qQEMpIhP6aZt-NPPEFcyE-G/view?usp=sharing

**Comment by jychien** [comment]
I downloaded the "Infant human neocortex cells" dataset from: https://cellxgene.cziscience.com/collections/e02201d7-f49f-401f-baf0-1eb1406546c0. And ran the 'remove-labels' on the 2.0.0 h5ad, and it correctly had logged saying that 2.0.0 is not supported, but then it resulted in a KeyError:

>  % cellxgene-schema remove-labels dropseq.h5ad dropseq_nolabels.h5ad
Loading dependencies
Loading h5ad from dropseq.h5ad
Schema version '2.0.0' is not supported. Current supported versions: '['3.0.0']'. Label removal cannot be performed.
Removing labels
Traceback (most recent call last):
  File "/opt/anaconda3/envs/cellxgene_cli_3.0.0/bin/cellxgene-schema", line 8, in <module>
    sys.exit(schema_cli())
  File "/opt/anaconda3/envs/cellxgene_cli_3.0.0/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/envs/cellxgene_cli_3.0.0/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/envs/cellxgene_cli_3.0.0/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/anaconda3/envs/cellxgene_cli_3.0.0/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/envs/cellxgene_cli_3.0.0/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/anaconda3/envs/cellxgene_cli_3.0.0/lib/python3.8/site-packages/cellxgene_schema/cli.py", line 78, in remove_labels
    anndata_label_remover.remove_labels()
  File "/opt/anaconda3/envs/cellxgene_cli_3.0.0/lib/python3.8/site-packages/cellxgene_schema/remove_labels.py", line 59, in remove_labels
    if "columns" in self.schema_def["components"][component_name]:
KeyError: 'components'

**Comment by nayib-jose-gloria** [comment]
Updated to address this bug, sent you a message with the new release candidate

**Comment by jychien** [comment]
Checked the following:
- removed appropriate fields from obs
- removed appropriate fields from var
- removed appropriate fields from raw.var

Looks good to me! :)
