### ISSUE TITLE
get_collections(visibility='PRIVATE') returns a 500. 

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#4097]
### Context

See [**single-cell-discover-api**](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1675209000173629).

`get_collections(visibility='PRIVATE')` returns a 500.

**Comment by danieljhegeman** [comment]
As produced by Brian's attempt in dev:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/dataclasses_json/core.py", line 263, in _decode_generic
    res = _get_type_cons(type_)(xs)
  File "/usr/local/lib/python3.10/dist-packages/dataclasses_json/core.py", line 317, in <genexpr>
    items = (_decode_dataclass(type_arg, x, infer_missing)
  File "/usr/local/lib/python3.10/dist-packages/dataclasses_json/core.py", line 137, in _decode_dataclass
    kvs = {decode_names.get(k, k): v for k, v in kvs.items()}
AttributeError: 'str' object has no attribute 'items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.10/dist-packages/connexion/decorators/decorator.py", line 68, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.10/dist-packages/connexion/security/security_handler_factory.py", line 388, in wrapper
    return function(request)
  File "/usr/local/lib/python3.10/dist-packages/connexion/decorators/uri_parsing.py", line 149, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.10/dist-packages/connexion/decorators/validation.py", line 399, in wrapper
    return function(request)
  File "/usr/local/lib/python3.10/dist-packages/connexion/decorators/response.py", line 112, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.10/dist-packages/connexion/decorators/parameter.py", line 116, in wrapper
    return function(**kwargs)
  File "/single-cell-data-portal/backend/curation/api/v1/curation/collections/actions.py", line 45, in get
    resp_collection = reshape_for_curation_api(collection_version, user_info, preview=True)
  File "/single-cell-data-portal/backend/curation/api/v1/curation/collections/common.py", line 104, in reshape_for_curation_api
    response_datasets = reshape_datasets_for_curation_api(
  File "/single-cell-data-portal/backend/curation/api/v1/curation/collections/common.py", line 142, in reshape_datasets_for_curation_api
    dataset_version = get_business_logic().get_dataset_version(dv) if isinstance(dv, DatasetVersionId) else dv
  File "/single-cell-data-portal/backend/layers/business/business.py", line 549, in get_dataset_version
    return self.database_provider.get_dataset_version(dataset_version_id)
  File "/single-cell-data-portal/backend/layers/persistence/persistence.py", line 444, in get_dataset_version
    return self._hydrate_dataset_version(dataset_version)
  File "/single-cell-data-portal/backend/layers/persistence/persistence.py", line 159, in _hydrate_dataset_version
    return self._row_to_dataset_version(dataset_version, canonical_dataset, artifacts)
  File "/single-cell-data-portal/backend/layers/persistence/persistence.py", line 141, in _row_to_dataset_version
    metadata = DatasetMetadata.from_json(row.dataset_metadata)
  File "/usr/local/lib/python3.10/dist-packages/dataclasses_json/api.py", line 65, in from_json
    return cls.from_dict(kvs, infer_missing=infer_missing)
  File "/usr/local/lib/python3.10/dist-packages/dataclasses_json/api.py", line 72, in from_dict
    return _decode_dataclass(cls, kvs, infer_missing)
  File "/usr/local/lib/python3.10/dist-packages/dataclasses_json/core.py", line 201, in _decode_dataclass
    init_kwargs[field.name] = _decode_generic(field_type,
  File "/usr/local/lib/python3.10/dist-packages/dataclasses_json/core.py", line 265, in _decode_generic
    res = type_(xs)
  File "/usr/lib/python3.10/typing.py", line 955, in __call__
    raise TypeError(f"Type {self._name} cannot be instantiated; "
TypeError: Type List cannot be instantiated; use list() instead
```

**Comment by danieljhegeman** [comment]
I have a feeling [this](https://github.com/lidatong/dataclasses-json/issues/294) is a similar issue but haven't confirmed

**Comment by danieljhegeman** [comment]
The problem is we have 10 datasets that are not conforming to the `[{"label": <str>, "ontology_term_id": <str>}...]` format on, in some cases, `organism` (raw object instead of list of objects), and in others, `sex` (array of `"male"` and/or `"female"`).
