### ISSUE TITLE
[Staging] ERROR: test_revision_flow (tests.functional.backend.corpora.test_revisions.TestRevisions) [Publishing a revised dataset replaces the original dataset]

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#4246]
Link: https://github.com/chanzuckerberg/single-cell-data-portal/actions/runs/4246355493/jobs/7384229865

> Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
  [Previous line repeated 4 more times]
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 836, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.cellxgene.staging.single-cell.czi.technology', port=443): Max retries exceeded with url: /dp/v1/datasets/meta?url=https://cellxgene.staging.single-cell.czi.technology/e/cad972fa-12a3-4ca3-a701-753c4b9fccb4.cxg/ (Caused by ResponseError('too many 500 error responses'))

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "/single-cell-data-portal/tests/functional/backend/corpora/test_revisions.py", line 122, in test_revision_flow
    dataset_meta_payload = self.session.get(f"{self.api}/dp/v1/datasets/meta?url={explorer_url}").json()
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 507, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='api.cellxgene.staging.single-cell.czi.technology', port=443): Max retries exceeded with url: /dp/v1/datasets/meta?url=https://cellxgene.staging.single-cell.czi.technology/e/cad972fa-12a3-4ca3-a701-753c4b9fccb4.cxg/ (Caused by ResponseError('too many 500 error responses'))

**Comment by nayib-jose-gloria** [comment]
this error is a result of https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/4245 failing; however, the attached PR should resolve the issue that causes this test (and the workflow its simulating) to be dependent on the result of the first test (and the workflow that's simulating)
