### ISSUE TITLE
[Staging] FAIL: test_secondary_filters_extreme_case (tests.functional.backend.wmg.test_wmg_api.TestWmgApi) 4 tissues w/largest cell type counts, 400 genes, no secondary filtering

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#4247]
Link: https://github.com/chanzuckerberg/single-cell-data-portal/actions/runs/4246355493/jobs/7384229865

> Traceback (most recent call last):
  File "/single-cell-data-portal/tests/functional/backend/wmg/test_wmg_api.py", line 54, in test_secondary_filters_extreme_case
    self.assertStatusCode(requests.codes.ok, res)
  File "/single-cell-data-portal/tests/functional/backend/common.py", line 125, in assertStatusCode
    self.assertEqual(actual, expected_response.status_code, msg=f"{request_id=}")
AssertionError: 200 != 504 : request_id=None

**Comment by tihuan** [comment]
@atarashansky can you help check if this is fixed? Thank you!
